### ISSUE TITLE
Store activity object UUID

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework-activities#5]
Requirement for #1. Dernormalizable needs to have easy access to this value and it makes sense to keep this is a column of its own.

**Comment by amazeika** [comment]
Missing commits are available on #2.

**Comment by johanjanssens** [comment]
@amazeika Can you please revert this change. We don't need to store the uuid in the activities table it only need to be stored in the resource table.

**Comment by amazeika** [comment]
@johanjanssens Reverted on #7

**Comment by johanjanssens** [comment]
Thanks!
